name: Automatisation Mensuelle Script V19

on:
  schedule:
    # S'exécute tous les 2 jours à 4h00 UTC (soit 5h00 du matin heure de Kinshasa)
    - cron: '0 4 */2 * *'
  workflow_dispatch: # Garde le gros bouton manuel sur le site GitHub

jobs:
  execution:
    runs-on: ubuntu-latest
    steps:
    - name: Récupérer le code du projet
      uses: actions/checkout@v4

    - name: Connexion à Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configurer les outils Google Cloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installer les bibliothèques requises
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Exécuter le script Python
      env:
        # On injecte ici les secrets DHIS2 pour que le script puisse s'y connecter
        DHIS2_USERG: ${{ secrets.DHIS2_USERG }}
        DHIS2_PASSWORDG: ${{ secrets.DHIS2_PASSWORDG }}
      run: python automation_dhis2_dqat_V19.py